# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for a single-file portable WordPress BAZOOKA executable.

Bundles:
  - all dynamically-discovered modules under modules/
  - the GUI templates and FastAPI app
  - the CVE seed DB and data wordlists
  - all transitive deps (httpx, FastAPI, Uvicorn, Jinja2, Pydantic, etc.)
"""

import os
from pathlib import Path
from PyInstaller.utils.hooks import collect_all

ROOT = Path(os.path.abspath(SPECPATH))

# Pull all playwright Python bits (driver, internals) so 'import playwright' works
# inside the frozen exe. The actual browser binary is NOT bundled (would add ~150MB);
# users still need to run `playwright install chromium` separately if they want it.
_pw_datas, _pw_binaries, _pw_hiddenimports = collect_all("playwright")

# Recursively collect every module under modules/ so dynamic discovery works
hidden_modules: list[str] = []
for folder in (ROOT / "modules").rglob("*.py"):
    rel = folder.relative_to(ROOT).with_suffix("")
    if rel.name == "__init__":
        rel = rel.parent
    hidden_modules.append(".".join(rel.parts))

# GUI app, report exporters, cve_db
hidden_modules += [
    "gui.app", "core.engine", "core.session", "core.models",
    "report.generator", "report.html_template", "report.docx_exporter",
    "cve_db.manager", "cve_db.wordfence_fetcher",
]

# Things FastAPI / Uvicorn / Starlette / Pydantic need that PyInstaller often misses
hidden_modules += [
    "uvicorn.logging", "uvicorn.loops", "uvicorn.loops.auto",
    "uvicorn.protocols", "uvicorn.protocols.http", "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets", "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan", "uvicorn.lifespan.on",
    "uvicorn.workers", "websockets",
    "anyio._backends._asyncio",
    "pydantic.deprecated.decorator",
    "email.mime.multipart", "email.mime.text", "email.mime.base",
    "dns.resolver", "dns.rdtypes", "dns.rdtypes.IN", "dns.rdtypes.ANY",
    # Optional integrations embedded so 'doctor' reports them as available.
    # NOTE: python-nmap / playwright / graphviz still need their system binary
    # (nmap, chromium, graphviz dot) when the host wants them effective.
    "nmap", "graphviz", "networkx",
]

datas = [
    ("data", "data"),
    ("gui/templates", "gui/templates"),
    ("cve_db/schema.sql", "cve_db"),
    ("cve_db/bazooka_cve.db", "cve_db"),
]

# Embed the prewarmed multi-source CVE bundle if available (~15-20 MB).
# Generated by `python -m cve_db.prewarm` or `bazooka update-db`.
_prewarm = ROOT / "cve_db" / "prewarm_cache.json"
if _prewarm.exists():
    datas.append((str(_prewarm), "cve_db"))

# Bundle Tor (Windows-only) so users can scan over Tor with --tor without
# installing anything. Adds ~19 MB to the exe.
_tor_root = ROOT / "vendor" / "tor"
if _tor_root.exists():
    if (_tor_root / "tor" / "tor.exe").exists():
        datas.append((str(_tor_root / "tor" / "tor.exe"), "vendor/tor/tor"))
    for fn in ("geoip", "torrc-defaults"):
        p = _tor_root / "data" / fn
        if p.exists():
            datas.append((str(p), "vendor/tor/data"))

# Static dir is optional
if (ROOT / "gui" / "static").exists():
    datas.append(("gui/static", "gui/static"))


a = Analysis(
    ['bazooka.py'],
    pathex=[str(ROOT)],
    binaries=_pw_binaries,
    datas=datas + _pw_datas,
    hiddenimports=hidden_modules + _pw_hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        'tkinter', 'matplotlib', 'pytest',
        'PyQt5', 'PyQt6', 'PySide2', 'PySide6',
        'IPython', 'ipykernel', 'notebook', 'jupyter',
        'pandas', 'numpy', 'scipy', 'sklearn',
        'PIL', 'PIL.Image', 'PIL.ImageFilter',
        'zmq', 'pyzmq',
        'black', 'lark',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='bazooka',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
