"""HTTP session manager with caching, throttling, UA rotation, and WAF-adaptive behavior."""

from __future__ import annotations

import asyncio
import hashlib
import random
import time
from typing import Any, Optional

import httpx
from rich.console import Console

import sys as _sys
console = Console(legacy_windows=False, force_terminal=_sys.stdout.isatty() if hasattr(_sys.stdout, "isatty") else False)

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0",
]

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-mitigated"],
        "body": ["cloudflare", "ray id"],
        "behavior": {"blocks_dotfiles": True, "generic_403_size": True, "challenges_js": True},
    },
    "SecuPress": {
        "headers": [],
        "body": ["secupress"],
        "behavior": {"blocks_dotfiles": True, "custom_login": True, "htpasswd_obfuscated": True},
    },
    "Wordfence": {
        "headers": [],
        "body": ["wordfence", "wfwaf-", "generated by wordfence"],
        "behavior": {"rate_limit_aggressive": True, "blocks_xmlrpc": False},
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body": ["sucuri", "access denied - sucuri"],
        "behavior": {"blocks_dotfiles": True, "generic_403_size": True},
    },
    "ModSecurity": {
        "headers": ["mod_security"],
        "body": ["mod_security", "modsecurity", "not acceptable"],
        "behavior": {"blocks_payloads": True},
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "body": ["request blocked"],
        "behavior": {"blocks_dotfiles": True, "generic_403_size": True},
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "akamai-grn"],
        "body": ["akamai", "reference #"],
        "behavior": {"blocks_dotfiles": True, "generic_403_size": True},
    },
    "Imperva": {
        "headers": ["x-iinfo", "x-cdn"],
        "body": ["incapsula", "imperva"],
        "behavior": {"blocks_dotfiles": True, "generic_403_size": True},
    },
    "OVH WAF": {
        "headers": [],
        "body": [],
        "behavior": {"generic_403_size": True},
    },
    "BunkerWeb": {
        "headers": [],
        "body": ["bunkerweb", "nothing to see here"],
        "behavior": {"blocks_everything": True},
    },
}


class ResponseCache:
    """In-memory cache with TTL + LRU bound (avoids memory leak on long scans)."""

    def __init__(self, max_size: int = 1000) -> None:
        from collections import OrderedDict
        self._cache: "OrderedDict[str, tuple[float, httpx.Response]]" = OrderedDict()
        self._max_size = max_size

    def _key(self, method: str, url: str, **kwargs: Any) -> str:
        raw = f"{method}:{url}:{sorted(kwargs.get('headers', {}).items())}"
        return hashlib.md5(raw.encode()).hexdigest()

    def get(self, method: str, url: str, ttl: float = 300, **kwargs: Any) -> Optional[httpx.Response]:
        key = self._key(method, url, **kwargs)
        if key in self._cache:
            ts, resp = self._cache[key]
            if time.time() - ts < ttl:
                self._cache.move_to_end(key)  # LRU touch
                return resp
            del self._cache[key]
        return None

    def put(self, method: str, url: str, response: httpx.Response, **kwargs: Any) -> None:
        key = self._key(method, url, **kwargs)
        self._cache[key] = (time.time(), response)
        self._cache.move_to_end(key)
        # Evict oldest entries beyond the cap
        while len(self._cache) > self._max_size:
            self._cache.popitem(last=False)

    def clear(self) -> None:
        self._cache.clear()


class WAFProfile:
    """WAF behavior profile — tells other modules how to adapt."""

    def __init__(self) -> None:
        self.name: Optional[str] = None
        self.detected: bool = False
        self.blocks_dotfiles: bool = False
        self.generic_403_size: bool = False
        self.challenges_js: bool = False
        self.custom_login: bool = False
        self.rate_limit_aggressive: bool = False
        self.blocks_payloads: bool = False
        self.blocks_everything: bool = False
        # Calibration data
        self.baseline_404_sizes: set[int] = set()
        self.baseline_403_sizes: set[int] = set()
        self.calibrated: bool = False

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "detected": self.detected,
            "blocks_dotfiles": self.blocks_dotfiles,
            "generic_403_size": self.generic_403_size,
            "rate_limit_aggressive": self.rate_limit_aggressive,
        }


class BazookaSession:
    """Intelligent HTTP session with retry, throttle, cache, UA rotation, and WAF adaptation."""

    def __init__(
        self,
        rate_limit: float = 10.0,
        timeout: float = 10.0,
        proxy: Optional[str] = None,
        custom_ua: Optional[str] = None,
        verify_ssl: bool = False,
    ) -> None:
        self.rate_limit = rate_limit
        self._original_rate_limit = rate_limit
        self.timeout = timeout
        self.proxy = proxy
        self.custom_ua = custom_ua
        self.verify_ssl = verify_ssl
        self.cache = ResponseCache()
        self.request_count = 0
        self._last_request_time = 0.0
        self._client: Optional[httpx.AsyncClient] = None
        self._consecutive_blocks = 0
        self.waf = WAFProfile()

    async def _get_client(self) -> httpx.AsyncClient:
        if self._client is None:
            transport = httpx.AsyncHTTPTransport(retries=2)
            self._client = httpx.AsyncClient(
                transport=transport,
                timeout=httpx.Timeout(self.timeout, connect=5.0),
                verify=self.verify_ssl,
                follow_redirects=True,
                proxy=self.proxy,
                limits=httpx.Limits(max_connections=20, max_keepalive_connections=10),
            )
        return self._client

    def _get_ua(self) -> str:
        if self.custom_ua:
            return self.custom_ua
        return random.choice(USER_AGENTS)

    async def _throttle(self) -> None:
        if self.rate_limit <= 0:
            return
        min_interval = 1.0 / self.rate_limit
        elapsed = time.time() - self._last_request_time
        if elapsed < min_interval:
            jitter = random.uniform(0, min_interval * 0.1)
            await asyncio.sleep(min_interval - elapsed + jitter)
        self._last_request_time = time.time()

    async def detect_waf(self, base_url: str) -> WAFProfile:
        """Proactive WAF detection — called once at scan start.
        Detects WAF from the homepage + a trigger request, then calibrates baselines."""

        # 1. Normal homepage request
        resp = await self.get(base_url)
        self._check_waf_signatures(resp)

        # 2. Trigger request with suspicious payload
        try:
            trigger_resp = await self.get(
                f"{base_url}/?bz_test=<script>alert(1)</script>",
                use_cache=False,
            )
            self._check_waf_signatures(trigger_resp)
        except Exception:
            pass

        # 3. Calibrate baseline responses (3 random 404 paths)
        for suffix in ["bz_cal_abc123", "bz_cal_xyz789.php", "bz_cal_dir456/test"]:
            try:
                cal_resp = await self.get(f"{base_url}/{suffix}", use_cache=False)
                size = len(cal_resp.content)
                if cal_resp.status_code == 404:
                    self.waf.baseline_404_sizes.add(size)
                    # Add tolerance band
                    self.waf.baseline_404_sizes.add(size - 5)
                    self.waf.baseline_404_sizes.add(size + 5)
                elif cal_resp.status_code == 403:
                    self.waf.baseline_403_sizes.add(size)
                    self.waf.baseline_403_sizes.add(size - 5)
                    self.waf.baseline_403_sizes.add(size + 5)
            except Exception:
                pass

        self.waf.calibrated = True

        # 4. Adapt session behavior based on WAF
        if self.waf.detected:
            if self.waf.rate_limit_aggressive:
                # Slow down to avoid ban
                self.rate_limit = min(self.rate_limit, 3.0)
            if self.waf.challenges_js:
                # Cloudflare JS challenge — note it for modules
                pass

        return self.waf

    def _check_waf_signatures(self, response: httpx.Response) -> None:
        """Check a response for WAF signatures."""
        headers_str = " ".join(f"{k.lower()} {v.lower()}" for k, v in response.headers.items())
        body = ""
        try:
            body = response.text[:3000].lower()
        except Exception:
            pass

        for waf_name, sig_data in WAF_SIGNATURES.items():
            found = False
            for h in sig_data["headers"]:
                if h.lower() in headers_str:
                    found = True
                    break
            if not found:
                for b in sig_data["body"]:
                    if b.lower() in body:
                        found = True
                        break
            if found:
                self.waf.name = waf_name
                self.waf.detected = True
                # Apply behavior profile
                behavior = sig_data.get("behavior", {})
                self.waf.blocks_dotfiles = behavior.get("blocks_dotfiles", False)
                self.waf.generic_403_size = behavior.get("generic_403_size", False)
                self.waf.challenges_js = behavior.get("challenges_js", False)
                self.waf.custom_login = behavior.get("custom_login", False)
                self.waf.rate_limit_aggressive = behavior.get("rate_limit_aggressive", False)
                self.waf.blocks_payloads = behavior.get("blocks_payloads", False)
                self.waf.blocks_everything = behavior.get("blocks_everything", False)
                return

    def is_waf_generic_page(self, status: int, content_size: int) -> bool:
        """Check if a response is a WAF generic block/not-found page."""
        if not self.waf.calibrated:
            return False

        if status == 404 and content_size in self.waf.baseline_404_sizes:
            return True
        if status == 403 and content_size in self.waf.baseline_403_sizes:
            return True
        # Cross-check: a 403 same size as 404 baseline = WAF transforming 404→403
        if status == 403 and content_size in self.waf.baseline_404_sizes:
            return True
        return False

    async def request(
        self,
        method: str,
        url: str,
        use_cache: bool = True,
        cache_ttl: float = 300,
        follow_redirects: bool = True,
        **kwargs: Any,
    ) -> httpx.Response:
        """Send an HTTP request with throttling, caching, and retry logic."""
        # Check cache first
        if use_cache and method.upper() == "GET":
            cached = self.cache.get(method, url, ttl=cache_ttl, **kwargs)
            if cached is not None:
                return cached

        await self._throttle()

        headers = kwargs.pop("headers", {})
        if "User-Agent" not in headers:
            headers["User-Agent"] = self._get_ua()
        kwargs["headers"] = headers
        kwargs["follow_redirects"] = follow_redirects

        client = await self._get_client()
        max_retries = 3

        for attempt in range(max_retries):
            try:
                response = await client.request(method, url, **kwargs)
                self.request_count += 1

                # Track blocking
                if response.status_code == 429:
                    self._consecutive_blocks += 1
                    retry_after = int(response.headers.get("Retry-After", "5"))
                    wait = min(retry_after, 30)
                    # Adaptive: slow down rate limit
                    if self._consecutive_blocks >= 3:
                        self.rate_limit = max(1.0, self.rate_limit * 0.5)
                    await asyncio.sleep(wait)
                    continue
                elif response.status_code == 403:
                    self._consecutive_blocks += 1
                    # If we're getting blocked repeatedly, slow down
                    if self._consecutive_blocks >= 10:
                        self.rate_limit = max(1.0, self.rate_limit * 0.7)
                        self._consecutive_blocks = 0
                else:
                    self._consecutive_blocks = max(0, self._consecutive_blocks - 1)

                # Cache successful GET responses
                if use_cache and method.upper() == "GET" and response.status_code < 400:
                    self.cache.put(method, url, response, **kwargs)

                return response

            except (httpx.ConnectError, httpx.ReadTimeout, httpx.ConnectTimeout):
                if attempt == max_retries - 1:
                    raise
                backoff = (2 ** attempt) + random.uniform(0, 1)
                await asyncio.sleep(backoff)

        raise httpx.ConnectError(f"Failed after {max_retries} retries: {url}")

    async def get(self, url: str, **kwargs: Any) -> httpx.Response:
        return await self.request("GET", url, **kwargs)

    async def post(self, url: str, **kwargs: Any) -> httpx.Response:
        return await self.request("POST", url, use_cache=False, **kwargs)

    async def head(self, url: str, **kwargs: Any) -> httpx.Response:
        return await self.request("HEAD", url, **kwargs)

    @property
    def waf_detected(self) -> Optional[str]:
        return self.waf.name if self.waf.detected else None

    async def close(self) -> None:
        if self._client:
            await self._client.aclose()
            self._client = None
